// frontend/src/components/users/AssignRoleDialog.vue
<template>
  <ui-dialog-shell
    :open="open"
    title="Назначить роль"
    description="Измените роль для выбранного пользователя"
    @close="handleClose"
  >
    <div v-if="user" class="assign-role-dialog">
      <div class="assign-role-dialog__user">
        <div class="assign-role-dialog__avatar" aria-hidden="true">
          {{ getUserInitials(user) }}
        </div>
        <div class="assign-role-dialog__user-copy">
          <div class="assign-role-dialog__name">
            {{ getUserDisplayLabel(user) }}
          </div>
          <div
            v-if="getUserTelegramLabel(user)"
            class="assign-role-dialog__telegram"
          >
            {{ getUserTelegramLabel(user) }}
          </div>
        </div>
      </div>

      <fieldset class="assign-role-dialog__fieldset" :disabled="isSaving">
        <legend class="assign-role-dialog__legend">Роль</legend>

        <v-radio-group
          v-model="selectedRole"
          class="assign-role-dialog__role-group"
          hide-details
          :disabled="isSaving"
        >
          <v-radio
            v-for="option in roleOptions"
            :key="option.value"
            class="assign-role-dialog__option"
            :class="{
              'assign-role-dialog__option--active':
                selectedRole === option.value,
            }"
            color="primary"
            name="assignedRole"
            :value="option.value"
          >
            <template #label>
              <span class="assign-role-dialog__option-copy">
                <span class="assign-role-dialog__option-title">
                  {{ option.label }}
                </span>
                <span class="assign-role-dialog__option-description">
                  {{ option.description }}
                </span>
              </span>
            </template>
          </v-radio>
        </v-radio-group>
      </fieldset>

      <p v-if="inlineError" class="assign-role-dialog__error">
        {{ inlineError }}
      </p>
    </div>

    <template #actions>
      <ui-button
        block
        :loading="isSaving"
        :disabled="isSubmitDisabled"
        @click="submitRole"
      >
        Назначить роль
      </ui-button>
      <ui-button
        block
        variant="ghost"
        :disabled="isSaving"
        @click="handleClose"
      >
        Отмена
      </ui-button>
    </template>
  </ui-dialog-shell>
</template>

<script setup lang="ts">
import { computed, ref, watch } from "vue";
import UiButton from "@/ui/UiButton.vue";
import UiDialogShell from "@/ui/UiDialogShell.vue";
import {
  getAssignableRoleInitialValue,
  getUserDisplayLabel,
  getUserInitials,
  getUserTelegramLabel,
} from "@/modules/users/presentation";
import type {
  AssignableUserRole,
  UserManagementUser,
} from "@/modules/users/types";
import { validateAssignRole } from "@/modules/users/validation";

const props = withDefaults(
  defineProps<{
    open: boolean;
    user: UserManagementUser | null;
    isSaving?: boolean;
    errorMessage?: string | null;
  }>(),
  {
    isSaving: false,
    errorMessage: null,
  },
);

const emit = defineEmits<{
  close: [];
  submit: [role: AssignableUserRole];
}>();

const roleOptions: readonly {
  readonly value: AssignableUserRole;
  readonly label: string;
  readonly description: string;
}[] = [
  {
    value: "barista",
    label: "Бариста",
    description: "Доступ к заказам и доступности",
  },
  {
    value: "administrator",
    label: "Администратор",
    description: "Полный доступ ко всем функциям",
  },
];

const selectedRole = ref<AssignableUserRole>("barista");
const validation = computed(() => validateAssignRole(selectedRole.value));
const inlineError = computed(
  () => validation.value.message ?? props.errorMessage,
);
const isSubmitDisabled = computed(
  () => props.isSaving || !validation.value.valid,
);

watch(
  () => [props.open, props.user?.userId, props.user?.roles.join(",")] as const,
  () => {
    if (props.open && props.user) {
      selectedRole.value = getAssignableRoleInitialValue(props.user.roles);
    }
  },
  { immediate: true },
);

function submitRole(): void {
  if (!validation.value.valid || !validation.value.payload) {
    return;
  }

  emit("submit", validation.value.payload.assignedRole);
}

function handleClose(): void {
  emit("close");
}
</script>

<style scoped lang="scss">
.assign-role-dialog {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.assign-role-dialog__user {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px;
  border-radius: var(--app-radius-md);
  background: var(--app-color-background-secondary);
}

.assign-role-dialog__avatar {
  flex: 0 0 40px;
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  background: var(--app-color-accent-light);
  color: var(--app-color-accent);
  font-size: 14px;
  line-height: 20px;
  font-weight: 500;
}

.assign-role-dialog__user-copy {
  min-width: 0;
}

.assign-role-dialog__name {
  overflow: hidden;
  color: var(--app-color-text-primary);
  font-size: 14px;
  line-height: 20px;
  font-weight: 600;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.assign-role-dialog__telegram {
  overflow: hidden;
  margin-top: 2px;
  color: var(--app-color-text-muted);
  font-size: 12px;
  line-height: 16px;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.assign-role-dialog__fieldset {
  display: flex;
  flex-direction: column;
  gap: 8px;
  min-width: 0;
  padding: 0;
  margin: 0;
  border: 0;
}

.assign-role-dialog__legend {
  padding: 0 0 4px;
  color: var(--app-color-text-secondary);
  font-size: 13px;
  line-height: 18px;
  font-weight: 500;
}

.assign-role-dialog__role-group {
  :deep(.v-selection-control-group) {
    gap: 8px;
  }
}

.assign-role-dialog__option {
  min-height: 70px;
  padding: 12px;
  border: 1px solid var(--app-color-border);
  border-radius: var(--app-radius-md);
  cursor: pointer;
  transition:
    background-color var(--app-motion-fast) var(--app-motion-easing),
    border-color var(--app-motion-fast) var(--app-motion-easing);
}

.assign-role-dialog__option :deep(.v-selection-control__wrapper) {
  margin-inline-end: 12px;
}

.assign-role-dialog__option :deep(.v-label) {
  flex: 1;
  min-width: 0;
  opacity: 1;
}

.assign-role-dialog__option:hover,
.assign-role-dialog__option--active {
  background: var(--app-color-background-secondary);
}

.assign-role-dialog__option--active {
  border-color: var(--app-color-accent);
}

.assign-role-dialog__option-copy {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.assign-role-dialog__option-title {
  color: var(--app-color-text-primary);
  font-size: 14px;
  line-height: 20px;
  font-weight: 600;
}

.assign-role-dialog__option-description {
  color: var(--app-color-text-muted);
  font-size: 12px;
  line-height: 16px;
}

.assign-role-dialog__error {
  margin: 0;
  color: var(--app-color-destructive);
  font-size: 13px;
  line-height: 20px;
}
</style>

// .references/Expressa_admin/src/app/components/AssignRoleDialog.tsx
import React, { useState, useEffect } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { Button } from './Button';
import { User, UserRole } from '../types';
import * as RadioGroup from '@radix-ui/react-radio-group';

interface AssignRoleDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onConfirm: (role: UserRole) => void;
  user: User | null;
}

export function AssignRoleDialog({
  open,
  onOpenChange,
  onConfirm,
  user,
}: AssignRoleDialogProps) {
  const [selectedRole, setSelectedRole] = useState<UserRole>('barista');

  useEffect(() => {
    if (user && open) {
      setSelectedRole(user.role);
    }
  }, [user, open]);

  const handleConfirm = () => {
    onConfirm(selectedRole);
    onOpenChange(false);
  };

  const handleCancel = () => {
    onOpenChange(false);
  };

  if (!user) return null;

  const getInitials = (name: string) => {
    return name.split(' ').map(n => n[0]).join('').toUpperCase();
  };

  return (
    <Dialog.Root open={open} onOpenChange={onOpenChange}>
      <Dialog.Portal>
        <Dialog.Overlay
          className="fixed inset-0 bg-[rgba(0,0,0,0.4)] z-50 animate-in fade-in duration-200"
          onClick={handleCancel}
        />
        <Dialog.Content className="fixed bottom-0 left-0 right-0 bg-white rounded-t-[16px] p-6 pb-safe z-50 md:bottom-auto md:top-1/2 md:left-1/2 md:-translate-x-1/2 md:-translate-y-1/2 md:rounded-[16px] md:max-w-md md:w-full max-h-[90vh] overflow-y-auto animate-in slide-in-from-bottom md:slide-in-from-top duration-200">
          <Dialog.Title className="text-lg font-semibold text-[#111111] mb-2">
            Назначить роль
          </Dialog.Title>
          <Dialog.Description className="text-sm text-[#555555] mb-6">
            Измените роль для выбранного пользователя
          </Dialog.Description>

          <div className="space-y-5 mb-6">
            {/* User Info */}
            <div className="flex items-center gap-3 p-3 bg-[#F5F5F7] rounded-[10px]">
              <div className="w-10 h-10 rounded-full bg-[#E8E8FF] flex items-center justify-center flex-shrink-0">
                <span className="text-sm font-medium text-[#1A1AFF]">
                  {getInitials(user.name)}
                </span>
              </div>
              <div className="flex-1 min-w-0">
                <div className="text-sm font-semibold text-[#111111]">{user.name}</div>
                {user.telegramUsername && (
                  <div className="text-xs text-[#999999] mt-0.5 truncate">{user.telegramUsername}</div>
                )}
              </div>
            </div>

            {/* Role Selection */}
            <div>
              <label className="block text-[13px] font-medium text-[#555555] mb-3">
                Роль
              </label>
              <RadioGroup.Root
                value={selectedRole}
                onValueChange={(value) => setSelectedRole(value as UserRole)}
                className="space-y-2"
              >
                <label className="flex items-center gap-3 p-3 rounded-[10px] border border-[#E0E0E0] cursor-pointer hover:bg-[#F5F5F7] transition-colors">
                  <RadioGroup.Item
                    value="barista"
                    className="w-5 h-5 rounded-full border-2 border-[#BDBDBD] data-[state=checked]:border-[#1A1AFF] data-[state=checked]:bg-[#1A1AFF] flex items-center justify-center"
                  >
                    <RadioGroup.Indicator className="w-2 h-2 rounded-full bg-white" />
                  </RadioGroup.Item>
                  <div className="flex-1">
                    <div className="text-sm font-semibold text-[#111111]">Бариста</div>
                    <div className="text-xs text-[#999999] mt-0.5">Доступ к заказам и доступности</div>
                  </div>
                </label>

                <label className="flex items-center gap-3 p-3 rounded-[10px] border border-[#E0E0E0] cursor-pointer hover:bg-[#F5F5F7] transition-colors">
                  <RadioGroup.Item
                    value="administrator"
                    className="w-5 h-5 rounded-full border-2 border-[#BDBDBD] data-[state=checked]:border-[#1A1AFF] data-[state=checked]:bg-[#1A1AFF] flex items-center justify-center"
                  >
                    <RadioGroup.Indicator className="w-2 h-2 rounded-full bg-white" />
                  </RadioGroup.Item>
                  <div className="flex-1">
                    <div className="text-sm font-semibold text-[#111111]">Администратор</div>
                    <div className="text-xs text-[#999999] mt-0.5">Полный доступ ко всем функциям</div>
                  </div>
                </label>
              </RadioGroup.Root>
            </div>
          </div>

          <div className="flex flex-col gap-2">
            <Button
              variant="primary"
              className="w-full"
              onClick={handleConfirm}
            >
              Назначить роль
            </Button>
            <Button variant="ghost" className="w-full" onClick={handleCancel}>
              Отмена
            </Button>
          </div>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}
